[project]
name = "backend"
version = "0.1.0"
description = ""
authors = [
    {name = "Your Name",email = "you@example.com"}
]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi (>=0.128.0,<0.129.0)",
    "uvicorn (>=0.40.0,<0.41.0)",
    "python-multipart (>=0.0.21,<0.0.22)",
    "gtts (>=2.5.4,<3.0.0)",
    "pillow (>=12.1.0,<13.0.0)",
    "opencv-python (>=4.12.0.88,<5.0.0.0)",
    "gdown (>=5.2.1,<6.0.0)",
    "torch (>=2.9.1,<3.0.0)",
    "librosa (>=0.11.0,<0.12.0)",
    "protobuf (<4.0.0)"
]

[tool.poetry]
packages = [{include = "backend", from = "src"}]

[[tool.poetry.source]]
name = "pytorch_cpu"
url = "https://download.pytorch.org/whl/cpu"
priority = "explicit"


[tool.poetry.dependencies]
torch = {source = "pytorch_cpu"}
[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
